# Generated by Django 4.2.9 on 2024-02-08 07:44

from django.db import migrations, models
import djchat.server.models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to=djchat.server.models.category_icon_uplpoad_path),
        ),
    ]
